name: settings_api
description: The interface and models for an API providing access to settings data. 
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
