name: settings_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  fasting_entities:
    path: ../../../domain/fasting_entities
  settings_api:
    path: ../../../infrastructure/settings_api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
