name: settings_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  # Needs fasting repo for the fasting window enum
  fasting_repository:
    path: ../fasting_repository

  settings_api:
    path: ../../abstract/settings_api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
