name: notifications_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.1

dependencies:
  logging: ^1.0.2
  notifications_api:
    path: ../../abstract/notifications_api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
