name: fasting_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
# dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
