name: local_fasting_api
description: An implementation of the FastingApi that uses Drift/sqllite.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
 fasting_api:
    path: ../../infrastructure/fasting_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
