name: local_fasting_api
description: An implementation of the FastingApi that uses Drift/sqllite.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
 drift: ^2.29.0
 sqlite3: ^2.9.4
 path_provider: ^2.1.5
 path: ^1.9.1

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  lints: ^5.0.0
  test: ^1.24.0
