name: fasting_use_cases
description: Package holding business logic wrapped in use cases 
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  fasting_repository:
    path: ../../domain/repositories/fasting_repository

  settings_repository:
    path: ../../domain/repositories/settings_repository

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
