name: fasting_repository
description: A repository that handles fasting related requests.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  fasting_api:
    path: ../../abstract/fasting_api
  fasting_domain:
    path: ../../fasting_domain

dev_dependencies:
  mocktail: ^1.0.4
  lints: ^6.0.0
  test: ^1.24.0
