name: fasting_repository
description: A repository that handles fasting related requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  local_fasting_api:
    path: ../../../infrastructure/local_fasting_api
  fasting_entities:
    path: ../../fasting_entities

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
