name: local_settings_api
description: An implementation of the SettingsApi that uses shared preferences. 
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
 shared_preferences: ^2.5.3
 settings_api:
    path: ../../data_providers/settings_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
